In [164]:
import pandas as pd
import numpy as np

## Data

In [165]:
participants = pd.read_csv("dataset/participants.tsv", sep="\t")
participants["participant_id"] = participants["participant_id"].str.replace("sub-", "subject_")
participants.sort_values(by="participant_id", inplace=True)
participants = participants[["participant_id", "Gender", "Age","MMSE", "Set","Group"]]
participants.head()

   participant_id Gender  Age  MMSE    Set Group
14    subject_001      F   57    16  Train     A
19    subject_002      F   78    22  Train     A
2     subject_003      M   70    14  Train     A
22    subject_004      F   67    20  Train     A
6     subject_005      M   70    22  Train     A

In [166]:
psd_features = pd.read_csv("dataset/PSDfeature_log.csv")
psd_features = psd_features[1:]
psd_features = psd_features.rename(columns={"Electrode": "participant_id"})
psd_features.head()

,participant_id,Fp1,Fp1.1,Fp1.2,Fp1.3,Fp1.4,Fp1.5,Fp1.6,Fp1.7,Fp1.8,...,Pz.12,Pz.13,Pz.14,Pz.15,Pz.16,Pz.17,Pz.18,Pz.19,Pz.20,Pz.21
1,subject_001,9955.750744832349,5166.757088224274,2507.7783854715112,2449.4957147055206,1202.8769155036616,1184.8606077291074,1183.8546644166197,1167.2503776620683,1178.0414195272645,...,1132.1434662598513,1119.8751620029557,6589.767520712642,6412.512109464831,6286.9907932815395,6179.468825137518,10068.675831653785,9878.417509178695,9668.294167555061,9468.60967595825
2,subject_002,9864.894480992405,5083.001366921116,2453.2522462945767,2442.8594648808867,1244.0615751740056,1284.567748621587,1282.5574331370124,1197.2759560149836,1181.8853870617354,...,1142.4370475921187,1131.8453508507898,6713.797219293133,6622.897760783629,6460.06660902327,6305.227791620774,10213.44761390513,9910.906189068324,9574.629415314415,9462.328771083121
3,subject_003,9856.737589801289,5159.567932436222,2535.202948389864,2529.867862781682,1252.632394342117,1296.274697661251,1286.8577290891144,1272.2699012755857,1229.6641377218666,...,1140.8838864514291,1140.975406677214,6649.246748882964,6506.370354074296,6348.642294116328,6201.893567401824,10178.596794997049,9871.239323192422,9613.606823837044,9397.156895390697
4,subject_004,9936.305097410488,5088.568334377931,2464.6522975064886,2435.856545783986,1190.2490932504352,1181.555355389323,1172.3596291627828,1158.801993339032,1146.683388787413,...,1118.7105235474387,1118.9605355607416,6559.930590131054,6441.948500249018,6271.595351354737,6170.692210760823,10081.682010297962,9934.645520652197,9869.659767973204,9800.93154051326
5,subject_005,9991.969760689726,5124.068578828951,2459.935883227152,2449.938166617991,1200.5624003857831,1204.1583310737658,1181.8413238829223,1177.2547484755955,1169.1377056452623,...,1144.1317018467696,1139.10580315039,6684.932045752222,6528.548586569237,6376.70905454886,6277.37089217015,10260.69440350689,10076.816839985975,9959.135854182116,10055.388243776808

In [167]:
df = pd.merge(psd_features, participants, on="participant_id")
df.sort_values(by="participant_id", inplace=True)
df["Gender"] = df["Gender"].map({"M": 1, "F": 0})
df.head()

,participant_id,Fp1,Fp1.1,Fp1.2,Fp1.3,Fp1.4,Fp1.5,Fp1.6,Fp1.7,Fp1.8,...,Pz.17,Pz.18,Pz.19,Pz.20,Pz.21,Gender,Age,MMSE,Set,Group
0,subject_001,9955.750744832349,5166.757088224274,2507.7783854715112,2449.4957147055206,1202.8769155036616,1184.8606077291074,1183.8546644166197,1167.2503776620683,1178.0414195272645,...,6179.468825137518,10068.675831653785,9878.417509178695,9668.294167555061,9468.60967595825,0,57,16,Train,A
1,subject_002,9864.894480992405,5083.001366921116,2453.2522462945767,2442.8594648808867,1244.0615751740056,1284.567748621587,1282.5574331370124,1197.2759560149836,1181.8853870617354,...,6305.227791620774,10213.44761390513,9910.906189068324,9574.629415314415,9462.328771083121,0,78,22,Train,A
2,subject_003,9856.737589801289,5159.567932436222,2535.202948389864,2529.867862781682,1252.632394342117,1296.274697661251,1286.8577290891144,1272.2699012755857,1229.6641377218666,...,6201.893567401824,10178.596794997049,9871.239323192422,9613.606823837044,9397.156895390697,1,70,14,Train,A
3,subject_004,9936.305097410488,5088.568334377931,2464.6522975064886,2435.856545783986,1190.2490932504352,1181.555355389323,1172.3596291627828,1158.801993339032,1146.683388787413,...,6170.692210760823,10081.682010297962,9934.645520652197,9869.659767973204,9800.93154051326,0,67,20,Train,A
4,subject_005,9991.969760689726,5124.068578828951,2459.935883227152,2449.938166617991,1200.5624003857831,1204.1583310737658,1181.8413238829223,1177.2547484755955,1169.1377056452623,...,6277.37089217015,10260.69440350689,10076.816839985975,9959.135854182116,10055.388243776808,1,70,22,Train,A

In [168]:
Train = df[df["Set"] == "Train"]
Test = df[df["Set"] == "Test"]

In [169]:
feature_cols = list(df.columns)[1:-5] # drop participant_id, Set, and Group
X_train = Train[feature_cols]
X_test = Test[feature_cols]

y_train = Train["Group"]
y_test = Test["Group"]

X_train.head()

,Fp1,Fp1.1,Fp1.2,Fp1.3,Fp1.4,Fp1.5,Fp1.6,Fp1.7,Fp1.8,Fp1.9,...,Pz.12,Pz.13,Pz.14,Pz.15,Pz.16,Pz.17,Pz.18,Pz.19,Pz.20,Pz.21
0,9955.750744832349,5166.757088224274,2507.7783854715112,2449.4957147055206,1202.8769155036616,1184.8606077291074,1183.8546644166197,1167.2503776620683,1178.0414195272645,1159.252421097811,...,1132.1434662598513,1119.8751620029557,6589.767520712642,6412.512109464831,6286.9907932815395,6179.468825137518,10068.675831653785,9878.417509178695,9668.294167555061,9468.60967595825
1,9864.894480992405,5083.001366921116,2453.2522462945767,2442.8594648808867,1244.0615751740056,1284.567748621587,1282.5574331370124,1197.2759560149836,1181.8853870617354,1170.0670913008305,...,1142.4370475921187,1131.8453508507898,6713.797219293133,6622.897760783629,6460.06660902327,6305.227791620774,10213.44761390513,9910.906189068324,9574.629415314415,9462.328771083121
2,9856.737589801289,5159.567932436222,2535.202948389864,2529.867862781682,1252.632394342117,1296.274697661251,1286.8577290891144,1272.2699012755857,1229.6641377218666,1201.0658384091287,...,1140.8838864514291,1140.975406677214,6649.246748882964,6506.370354074296,6348.642294116328,6201.893567401824,10178.596794997049,9871.239323192422,9613.606823837044,9397.156895390697
3,9936.305097410488,5088.568334377931,2464.6522975064886,2435.856545783986,1190.2490932504352,1181.555355389323,1172.3596291627828,1158.801993339032,1146.683388787413,1150.298984174195,...,1118.7105235474387,1118.9605355607416,6559.930590131054,6441.948500249018,6271.595351354737,6170.692210760823,10081.682010297962,9934.645520652197,9869.659767973204,9800.93154051326
4,9991.969760689726,5124.068578828951,2459.935883227152,2449.938166617991,1200.5624003857831,1204.1583310737658,1181.8413238829223,1177.2547484755955,1169.1377056452623,1169.7255103866985,...,1144.1317018467696,1139.10580315039,6684.932045752222,6528.548586569237,6376.70905454886,6277.37089217015,10260.69440350689,10076.816839985975,9959.135854182116,10055.388243776808

In [170]:
X_train["Fp1"]

0      9955.750744832349
1      9864.894480992405
2      9856.737589801289
3      9936.305097410488
4      9991.969760689726
             ...
82     9956.236001134504
83     9810.448558964838
85    10512.212989426469
86      9992.68140950664
87      9918.29446200607
Name: Fp1, Length: 68, dtype: object

### Binary Data (only Healthy and AD)

In [171]:
binary_df = df[(df['Group'] == 'A') | (df['Group'] == 'C')]
Binary_Train = binary_df[binary_df["Set"] == "Train"]
Binary_Test = binary_df[binary_df["Set"] == "Test"]

Binary_X_train = Binary_Train[feature_cols]
Binary_X_test = Binary_Test[feature_cols]

Binary_X_train = Binary_X_train.astype(float)
Binary_X_test = Binary_X_test.astype(float)

Binary_y_train = Binary_Train["Group"]
Binary_y_test = Binary_Test["Group"]

In [172]:
Binary_X_train[["T5.1","T5.10","T5.18","Fp2.1","Fp2.10","Fp2.18",]].describe()

,T5.1,T5.10,T5.18,Fp2.1,Fp2.10,Fp2.18
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,5145.116592,1212.385322,10554.713151,5144.473093,1181.098071,10557.139808
std,49.400169,53.197219,241.713612,72.858928,38.531626,320.926272
min,5082.113475,1145.771983,10231.378465,5075.378438,1130.000414,10101.680038
25%,5112.621485,1173.826568,10330.558510,5106.900071,1155.081778,10351.836565
50%,5128.467075,1198.570114,10550.936893,5119.191644,1170.623145,10467.105827
75%,5162.949129,1230.329553,10656.057426,5159.735761,1201.621730,10700.087668
max,5304.922011,1362.253661,11234.146145,5437.151646,1293.715284,11850.992678

## Models
#### Binary Classification between Healthy and AD

In [173]:
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import classification_report, accuracy_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

### Decision Tree

In [174]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

y_pred_dt = cross_val_predict(dt_model, Binary_X_train, Binary_y_train, cv=cv)

accuracy_dt = accuracy_score(Binary_y_train, y_pred_dt)
report_dt = classification_report(Binary_y_train, y_pred_dt, target_names=["Alzheimer", "Control"])

print("Decision Tree Results:")
print(f"Train Accuracy: {accuracy_dt:.4f}")
print(f"Classification Report:\n{report_dt}")

Decision Tree Results:
Train Accuracy: 0.6600
Classification Report:
              precision    recall  f1-score   support

   Alzheimer       0.70      0.68      0.69        28
     Control       0.61      0.64      0.62        22

    accuracy                           0.66        50
   macro avg       0.66      0.66      0.66        50
weighted avg       0.66      0.66      0.66        50

### Random Forest

In [175]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(Binary_X_train, Binary_y_train)

y_pred_rf = cross_val_predict(rf_model, Binary_X_train, Binary_y_train, cv=cv)

accuracy_rf = accuracy_score(Binary_y_train, y_pred_rf)
report_rf = classification_report(Binary_y_train, y_pred_rf, target_names=["Alzheimer", "Control"])

print("\nRandom Forest Results:")
print(f"Train Accuracy: {accuracy_rf}")
print(f"Classification Report:\n{report_rf}")

Random Forest Results:
Train Accuracy: 0.84
Classification Report:
              precision    recall  f1-score   support

   Alzheimer       0.88      0.82      0.85        28
     Control       0.79      0.86      0.83        22

    accuracy                           0.84        50
   macro avg       0.84      0.84      0.84        50
weighted avg       0.84      0.84      0.84        50

### XGBoost

In [155]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

In [176]:
xgb_model = XGBClassifier(eval_metric="mlogloss", random_state=42)

label_encoder = LabelEncoder()
Binary_y_train_xgb = label_encoder.fit_transform(Binary_y_train)

xgb_model.fit(Binary_X_train, Binary_y_train_xgb)

y_pred_xgb = cross_val_predict(xgb_model, Binary_X_train, Binary_y_train_xgb, cv=cv)

accuracy_xgb = accuracy_score(Binary_y_train_xgb, y_pred_xgb)
report_xgb = classification_report(Binary_y_train_xgb, y_pred_xgb, target_names=["Alzheimer", "Control"])

print("\nXGBoost Results:")
print(f"Train Accuracy: {accuracy_xgb}")
print(f"Classification Report:\n{report_xgb}")

XGBoost Results:
Train Accuracy: 0.76
Classification Report:
              precision    recall  f1-score   support

   Alzheimer       0.79      0.79      0.79        28
     Control       0.73      0.73      0.73        22

    accuracy                           0.76        50
   macro avg       0.76      0.76      0.76        50
weighted avg       0.76      0.76      0.76        50

# Hyper-Parameter Tuning + Cross Validation

In [ ]:
from sklearn.model_selection import GridSearchCV

rf_param_grid = {
    "n_estimators": [50, 100, 150, 200, 300, 400],
    "max_depth": [3, 5, 7, 9],
    "min_samples_split": [2, 4, 6, 8],
    "min_samples_leaf": [2, 4, 6]  
}

dt_param_grid = {
    "max_depth": list(np.arange(3, 11, 1)) +  [None],
    "min_samples_split": np.arange(2, 11, 1),
    "min_samples_leaf": [1, 2, 3, 4, 5]
}

xgb_param_grid = {
    "n_estimators": [50, 100, 150, 200, 300, 400],
    "max_depth": list(np.arange(3, 11, 1)) +  [None],
    "learning_rate": [0.001, 0.005, 0.01, 0.05, 0.1, 0.15, 0.2],
    "subsample": [0.8, 1.0]
}

In [158]:
def cross_val_and_tune(model, param_grid, X, y, xgboost=False):
    if xgboost:
        label_encoder = LabelEncoder()
        y = label_encoder.fit_transform(y)
        X = X.astype("float32")

    grid_search = GridSearchCV(model, param_grid, cv=5, scoring="accuracy", n_jobs=-1, verbose=1)
    grid_search.fit(X, y)
    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    return best_model, best_params, best_score

In [159]:
best_rf, rf_params, rf_score = cross_val_and_tune(RandomForestClassifier(random_state=42), rf_param_grid, Binary_X_train, Binary_y_train)
best_dt, dt_params, dt_score = cross_val_and_tune(DecisionTreeClassifier(random_state=42), dt_param_grid, Binary_X_train, Binary_y_train)
best_xgb, xgb_params, xgb_score = cross_val_and_tune(XGBClassifier(eval_metric="mlogloss", random_state=42), xgb_param_grid, Binary_X_train, Binary_y_train, xgboost=True)


tuning_results = {
    "Decision Tree": {"Best Params": dt_params, "Best Score": dt_score},
    "Random Forest": {"Best Params": rf_params, "Best Score": rf_score},
    "XGBoost": {"Best Params": xgb_params, "Best Score": xgb_score}
}

tuning_df = pd.DataFrame(tuning_results).T

Fitting 5 folds for each of 288 candidates, totalling 1440 fits
Fitting 5 folds for each of 405 candidates, totalling 2025 fits
Fitting 5 folds for each of 756 candidates, totalling 3780 fits

In [104]:
tuning_df

                                                     Best Params Best Score
Decision Tree  {'max_depth': 3, 'min_samples_leaf': 3, 'min_s...        0.7
Random Forest  {'max_depth': 3, 'min_samples_leaf': 2, 'min_s...       0.84
XGBoost        {'learning_rate': 0.1, 'max_depth': 3, 'n_esti...       0.86

In [162]:
tuning_df['Best Params'].iloc[2]

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}

## Tuned Models

In [180]:
dt_model = DecisionTreeClassifier(max_depth=3, min_samples_leaf=3, min_samples_split=2, random_state=42)

dt_model.fit(Binary_X_train,Binary_y_train)

y_pred_dt = dt_model.predict(Binary_X_test)

accuracy_dt = accuracy_score(Binary_y_test, y_pred_dt)
report_dt = classification_report(Binary_y_test, y_pred_dt, target_names=["Alzheimer", "Control"])

print("Decision Tree (Tuned) Results:")
print(f"Test Accuracy: {accuracy_dt:.4f}")
print(f"Classification Report:\n{report_dt}")

Decision Tree (Tuned) Results:
Test Accuracy: 0.6000
Classification Report:
              precision    recall  f1-score   support

   Alzheimer       0.67      0.50      0.57         8
     Control       0.56      0.71      0.62         7

    accuracy                           0.60        15
   macro avg       0.61      0.61      0.60        15
weighted avg       0.61      0.60      0.60        15

In [181]:
rf_model = RandomForestClassifier(max_depth=3, min_samples_leaf=2, min_samples_split=2, n_estimators=300, random_state=42)
rf_model.fit(Binary_X_train, Binary_y_train)

y_pred_rf = rf_model.predict(Binary_X_test)

accuracy_rf = accuracy_score(Binary_y_test, y_pred_rf)
report_rf = classification_report(Binary_y_test, y_pred_rf, target_names=["Alzheimer", "Control"])

print("Random Forest (Tuned) Results:")
print(f"Test Accuracy: {accuracy_rf}")
print(f"Classification Report:\n{report_rf}")

Random Forest (Tuned) Results:
Test Accuracy: 0.6666666666666666
Classification Report:
              precision    recall  f1-score   support

   Alzheimer       0.71      0.62      0.67         8
     Control       0.62      0.71      0.67         7

    accuracy                           0.67        15
   macro avg       0.67      0.67      0.67        15
weighted avg       0.67      0.67      0.67        15

In [182]:
label_encoder = LabelEncoder()

Binary_y_train_xgb = label_encoder.fit_transform(Binary_y_train)
Binary_y_test_xgb = label_encoder.fit_transform(Binary_y_test)

xgb_model = XGBClassifier(eval_metric="mlogloss", n_estimators=100, max_depth=3, learning_rate=0.01, subsample=0.8, random_state=42)
xgb_model.fit(Binary_X_train, Binary_y_train_xgb)

y_pred_xgb = xgb_model.predict(Binary_X_test)

accuracy_xgb = accuracy_score(Binary_y_test_xgb, y_pred_xgb)
report_xgb = classification_report(Binary_y_test_xgb, y_pred_xgb, target_names=["Alzheimer's", "Healthy"])

print("\nXGBoost Results:")
print(f"Accuracy: {accuracy_xgb}")
print(f"Classification Report:\n{report_xgb}")

XGBoost Results:
Accuracy: 0.6
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.60      0.75      0.67         8
     Healthy       0.60      0.43      0.50         7

    accuracy                           0.60        15
   macro avg       0.60      0.59      0.58        15
weighted avg       0.60      0.60      0.59        15