In [45]:
import pandas as pd

## Data

In [46]:
participants = pd.read_csv("dataset/participants.tsv", sep="\t")
participants["participant_id"] = participants["participant_id"].str.replace("sub-", "subject_")
participants.sort_values(by="participant_id", inplace=True)
participants = participants[["participant_id", "Gender", "Age","MMSE", "Set","Group"]]
participants

   participant_id Gender  Age  MMSE    Set Group
14    subject_001      F   57    16  Train     A
19    subject_002      F   78    22  Train     A
2     subject_003      M   70    14  Train     A
22    subject_004      F   67    20  Train     A
6     subject_005      M   70    22  Train     A
..            ...    ...  ...   ...    ...   ...
83    subject_084      F   71    24  Train     F
76    subject_085      M   64    26   Test     F
66    subject_086      M   49    26  Train     F
68    subject_087      M   73    24  Train     F
73    subject_088      M   55    24  Train     F

[88 rows x 6 columns]

In [47]:
psd_features = pd.read_csv("dataset/PSDfeature.csv")
psd_features = psd_features[1:]
psd_features = psd_features.rename(columns={"Electrode": "participant_id"})
psd_features

,participant_id,Fp1,Fp1.1,Fp1.2,Fp1.3,Fp1.4,Fp1.5,Fp1.6,Fp1.7,Fp1.8,...,Pz.6,Pz.7,Pz.8,Pz.9,Pz.10,Pz.11,Pz.12,Pz.13,Pz.14,Pz.15
1,subject_001,352928252755.4908,1890134908472.2983,2513720924741.8755,1730135836415.3828,1068808449438.9093,816532597277.6555,450333524776.2763,392079362880.70844,279781002372.50543,...,426607878616.5642,403623538422.2653,268698491840.92984,328819728461.99725,331285410329.3239,237152460456.57224,176350384225.52847,138195007528.35443,101490067685.88838,25080403023.118763
2,subject_002,173921669575.9071,2360292239843.03,2283920283596.212,1620653645774.5916,1090091079938.5887,529550628353.0432,507347557000.87946,388052170433.2117,247165689482.69193,...,504147446234.6904,410903433897.621,256709656330.27966,264726935613.03256,260639357222.9376,228667217165.36487,165108709921.6372,126555539481.62077,89635914074.06128,66810013211.44177
3,subject_003,254152312082.85745,2014220668073.8486,1899599590292.1042,1143379183079.6267,647677981134.627,552521344672.5972,429871471983.0968,323625067834.4773,232588123793.4999,...,413117436778.2594,308478019313.68726,221116376540.98248,212842800754.13242,301166636519.2435,199631753655.66745,121046626929.61063,117967574697.53253,104077662728.55078,154588573235.80823
4,subject_004,286345447220.4042,2229562214582.348,3352909139189.1646,1512736459493.238,954715916657.9564,819208737816.0454,551977949396.6342,322861679951.27185,289828397243.7718,...,492246266847.4467,348408923762.938,317576881708.65814,203879618176.20483,407059115247.8955,221077093315.32513,183763798599.35492,122842917762.74422,95218070248.69952,26250492727.431217
5,subject_005,538677961921.8651,2682647000845.9307,3261899437844.0093,1595647841268.2593,1124835946754.6436,871680745634.1992,590791894695.5498,412088543632.4649,333668160983.9055,...,540373660273.6598,376284831751.04425,300566378531.3502,216023528774.22916,359992242186.4219,232043083946.41937,181127380996.88632,125699963391.30315,105485529761.90166,32373135028.625504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,subject_084,314500619846.9256,2025837035788.9583,1847746397436.5876,1004348488874.9993,724654170221.2661,432837817298.2745,320464159667.7868,271119273623.70358,246705055802.2816,...,356418787220.3256,284503551888.6819,266890819314.12677,178825469094.54025,266693174226.3244,206211795623.15994,136047626734.64912,112742041036.9259,93969142405.36746,30020878435.839333
85,subject_085,378981954156.7592,2399304041605.726,3040985256872.113,2035262793236.1145,1331730843529.4314,723454386319.1805,757638272514.7719,443379931409.4608,416236514058.1,...,652719181697.6193,409134134327.46075,372624327801.95496,251372199939.3673,416933229791.51373,328794207480.04675,207831283042.87073,156430529710.11682,129542820529.9129,34011943226.583508
86,subject_086,5031700868965.933,11244145715125.305,9806245583620.262,6875213689235.164,3111595352475.377,2586388364822.6533,1816054645426.7498,1427711358278.0955,1015796037679.0522,...,1213324927838.58,901704456384.3574,604439067171.6598,450175964577.78143,669159752670.5754,485135181814.4372,305865811035.44434,189309565500.11206,130319359028.4401,66891594850.43176
87,subject_087,466760881059.1044,2305345452646.499,2562040170246.5776,1697714998944.0657,1432973497108.9116,942439137753.3749,505173990808.4644,534012594048.1812,330664359342.3533,...,454874926048.4799,488871225702.9638,310189956716.7424,242035831375.33823,355351311899.7761,260793001909.63373,164970908728.62802,122780590691.02173,125537859139.78178,27782869405.416397
88,subject_088,266828369979.9153,2060440293445.0305,2112694968938.7087,1397510384337.73,951422593120.3917,790519222504.8873,502018913619.18274,370170665563.8182,315257472281.9697,...,494400293841.42975,361831927200.94226,290067229849.31744,243203124639.47043,323798087124.32635,231516413793.0999,173677129929.72446,118655625607.74886,102096612183.98117,70873608545.37581

In [48]:
df = pd.merge(psd_features, participants, on="participant_id")
df.sort_values(by="participant_id", inplace=True)
df["Gender"] = df["Gender"].map({"M": 1, "F": 0})
df

,participant_id,Fp1,Fp1.1,Fp1.2,Fp1.3,Fp1.4,Fp1.5,Fp1.6,Fp1.7,Fp1.8,...,Pz.11,Pz.12,Pz.13,Pz.14,Pz.15,Gender,Age,MMSE,Set,Group
0,subject_001,352928252755.4908,1890134908472.2983,2513720924741.8755,1730135836415.3828,1068808449438.9093,816532597277.6555,450333524776.2763,392079362880.70844,279781002372.50543,...,237152460456.57224,176350384225.52847,138195007528.35443,101490067685.88838,25080403023.118763,0,57,16,Train,A
1,subject_002,173921669575.9071,2360292239843.03,2283920283596.212,1620653645774.5916,1090091079938.5887,529550628353.0432,507347557000.87946,388052170433.2117,247165689482.69193,...,228667217165.36487,165108709921.6372,126555539481.62077,89635914074.06128,66810013211.44177,0,78,22,Train,A
2,subject_003,254152312082.85745,2014220668073.8486,1899599590292.1042,1143379183079.6267,647677981134.627,552521344672.5972,429871471983.0968,323625067834.4773,232588123793.4999,...,199631753655.66745,121046626929.61063,117967574697.53253,104077662728.55078,154588573235.80823,1,70,14,Train,A
3,subject_004,286345447220.4042,2229562214582.348,3352909139189.1646,1512736459493.238,954715916657.9564,819208737816.0454,551977949396.6342,322861679951.27185,289828397243.7718,...,221077093315.32513,183763798599.35492,122842917762.74422,95218070248.69952,26250492727.431217,0,67,20,Train,A
4,subject_005,538677961921.8651,2682647000845.9307,3261899437844.0093,1595647841268.2593,1124835946754.6436,871680745634.1992,590791894695.5498,412088543632.4649,333668160983.9055,...,232043083946.41937,181127380996.88632,125699963391.30315,105485529761.90166,32373135028.625504,1,70,22,Train,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,subject_084,314500619846.9256,2025837035788.9583,1847746397436.5876,1004348488874.9993,724654170221.2661,432837817298.2745,320464159667.7868,271119273623.70358,246705055802.2816,...,206211795623.15994,136047626734.64912,112742041036.9259,93969142405.36746,30020878435.839333,0,71,24,Train,F
84,subject_085,378981954156.7592,2399304041605.726,3040985256872.113,2035262793236.1145,1331730843529.4314,723454386319.1805,757638272514.7719,443379931409.4608,416236514058.1,...,328794207480.04675,207831283042.87073,156430529710.11682,129542820529.9129,34011943226.583508,1,64,26,Test,F
85,subject_086,5031700868965.933,11244145715125.305,9806245583620.262,6875213689235.164,3111595352475.377,2586388364822.6533,1816054645426.7498,1427711358278.0955,1015796037679.0522,...,485135181814.4372,305865811035.44434,189309565500.11206,130319359028.4401,66891594850.43176,1,49,26,Train,F
86,subject_087,466760881059.1044,2305345452646.499,2562040170246.5776,1697714998944.0657,1432973497108.9116,942439137753.3749,505173990808.4644,534012594048.1812,330664359342.3533,...,260793001909.63373,164970908728.62802,122780590691.02173,125537859139.78178,27782869405.416397,1,73,24,Train,F
87,subject_088,266828369979.9153,2060440293445.0305,2112694968938.7087,1397510384337.73,951422593120.3917,790519222504.8873,502018913619.18274,370170665563.8182,315257472281.9697,...,231516413793.0999,173677129929.72446,118655625607.74886,102096612183.98117,70873608545.37581,1,55,24,Train,F

In [49]:
Train = df[df["Set"] == "Train"]
Test = df[df["Set"] == "Test"]

In [50]:
feature_cols = list(df.columns)[1:-2] # drop participant_id, Set, and Group
X_train = Train[feature_cols]
X_test = Test[feature_cols]

y_train = Train["Group"]
y_test = Test["Group"]

### Binary Data (only Healthy and AD)

In [51]:
binary_df = df[(df['Group'] == 'A') | (df['Group'] == 'F')]
Binary_Train = binary_df[binary_df["Set"] == "Train"]
Binary_Test = binary_df[binary_df["Set"] == "Test"]
Binary_X_train = Binary_Train[feature_cols]
Binary_X_test = Binary_Test[feature_cols]

Binary_y_train = Binary_Train["Group"]
Binary_y_test = Binary_Test["Group"]

In [52]:
Binary_X_train.shape

(46, 307)

## Models
#### Binary Classification between Healthy and AD

### Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

def decision_tree_classifier(X_train, y_train, X_test, y_test):
    dt_model = DecisionTreeClassifier(random_state=42)
    # dt_model = DecisionTreeClassifier()
    dt_model.fit(X_train, y_train)


    y_pred_dt = dt_model.predict(X_test)


    accuracy_dt = accuracy_score(y_test, y_pred_dt)
    # report_dt = classification_report(y_test, y_pred_dt, target_names=["Alzheimer's", "FTD", "Healthy"])
    report_dt = classification_report(y_test, y_pred_dt, target_names=["Alzheimer's", "Healthy"])

    print("Decision Tree Results:")
    print(f"Accuracy: {accuracy_dt}")
    print(f"Classification Report:\n{report_dt}")

In [37]:
decision_tree_classifier(Binary_X_train, Binary_y_train, Binary_X_test, Binary_y_test)

Decision Tree Results:
Accuracy: 0.7692307692307693
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.78      0.88      0.82         8
     Healthy       0.75      0.60      0.67         5

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13

### Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier

def random_forest_classifier(X_train, y_train, X_test, y_test):
    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
    rf_model.fit(X_train, y_train)


    y_pred_rf = rf_model.predict(X_test)


    accuracy_rf = accuracy_score(y_test, y_pred_rf)
    # report_rf = classification_report(y_test, y_pred_rf, target_names=["Alzheimer's", "FTD", "Healthy"])
    report_rf = classification_report(y_test, y_pred_rf, target_names=["Alzheimer's", "Healthy"])


    print("\nRandom Forest Results:")
    print(f"Accuracy: {accuracy_rf}")
    print(f"Classification Report:\n{report_rf}")

In [38]:
random_forest_classifier(Binary_X_train, Binary_y_train, Binary_X_test, Binary_y_test)

Random Forest Results:
Accuracy: 0.6153846153846154
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.64      0.88      0.74         8
     Healthy       0.50      0.20      0.29         5

    accuracy                           0.62        13
   macro avg       0.57      0.54      0.51        13
weighted avg       0.58      0.62      0.56        13

### XGBoost

In [35]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

In [36]:
def xgboost_classifier(X_train, y_train, X_test, y_test):
    label_encoder = LabelEncoder()

    y_train = label_encoder.fit_transform(y_train)
    y_test = label_encoder.transform(y_test)
    X_train = X_train.astype("float32")
    X_test = X_test.astype("float32")

    xgb_model = XGBClassifier(use_label_encoder=False, eval_metric="mlogloss", random_state=42)
    xgb_model.fit(X_train, y_train)

    y_pred_xgb = xgb_model.predict(X_test)

    accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
    # report_xgb = classification_report(y_test, y_pred_xgb, target_names=["Alzheimer's", "FTD", "Healthy"])
    report_xgb = classification_report(y_test, y_pred_xgb, target_names=["Alzheimer's", "Healthy"])

    print("\nXGBoost Results:")
    print(f"Accuracy: {accuracy_xgb}")
    print(f"Classification Report:\n{report_xgb}")

In [39]:
xgboost_classifier(Binary_X_train, Binary_y_train, Binary_X_test, Binary_y_test)

XGBoost Results:
Accuracy: 0.7692307692307693
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.78      0.88      0.82         8
     Healthy       0.75      0.60      0.67         5

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13

# Remove Useless Electrodes

In [40]:
# Useless electrodes based on plots from EDA.ipynb
remove_electrodes = ["C3", "C4", "P4", "F7", "T3", "Fz", "Cz", "Pz"]
useful_electrodes = [col for col in X_train.columns if col[:2] not in remove_electrodes]

In [53]:
Binary_X_train_less = Binary_X_train[useful_electrodes]
Binary_X_test_less = Binary_X_test[useful_electrodes]

In [54]:
Binary_X_train_less.shape

(46, 179)

In [55]:
decision_tree_classifier(Binary_X_train_less, Binary_y_train, Binary_X_test_less, Binary_y_test)

Decision Tree Results:
Accuracy: 0.6153846153846154
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.71      0.62      0.67         8
     Healthy       0.50      0.60      0.55         5

    accuracy                           0.62        13
   macro avg       0.61      0.61      0.61        13
weighted avg       0.63      0.62      0.62        13

In [56]:
random_forest_classifier(Binary_X_train_less, Binary_y_train, Binary_X_test_less, Binary_y_test)

Random Forest Results:
Accuracy: 0.46153846153846156
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.55      0.75      0.63         8
     Healthy       0.00      0.00      0.00         5

    accuracy                           0.46        13
   macro avg       0.27      0.38      0.32        13
weighted avg       0.34      0.46      0.39        13

In [57]:
xgboost_classifier(Binary_X_train_less, Binary_y_train, Binary_X_test_less, Binary_y_test)

XGBoost Results:
Accuracy: 0.7692307692307693
Classification Report:
              precision    recall  f1-score   support

 Alzheimer's       0.78      0.88      0.82         8
     Healthy       0.75      0.60      0.67         5

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13

## Hyper-Parameter Tuning + Cross Validation